server:
  port: 8081

service:
  name: org.kotliner.sample.service.bar

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/