server:
  port: 8082

service: 
  name: org.kotliner.sample.service.foo

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/